### ISSUE TITLE
Html worker request

### ISSUE THREAD

**Issue by danyaPostfactum** [ajaxorg/ace#1181]
Can not find htmllint.js or htmltidy.js . Does anybody know useful stuff for html parsing and linting written in javascript (or maybe in python)?

**Comment by mutlucan96** [comment]
Anything new?

**Comment by qcho** [comment]
Hey! whats the status on this issue? I would love to have proper xml-schema or relaxng validation and completion based on provided schema.
Obviously html seems not to be the perfect case because it's not strict xml as @danyaPostfactum is pointing out. So...

Is there any design though by collaborators / ace elders on this topic?
Should we continue the discussion elsewhere appart from html since it seems xml validation is not capable of validate the most weird html cases? Should we discard this weird cases because practically no one will want to validate a non-xml file?

Related #3486
