### ISSUE TITLE
Cursor positioned incorrectly with Unicode diacritic

### ISSUE THREAD

**Issue by loganfsmyth** [ajaxorg/ace#1531]
[Diacritics](http://en.wikipedia.org/wiki/Combining_character) and other combining characters should not be included when calculating the horizontal position of the cursor since are rendered as part of the previous character.

Example:
Paste 'V̇' into Ace.

Result:
The cursor shows up after the newline marker because the diacritic is counting as a character. ![Screenshot](https://f.cloud.github.com/assets/132260/845150/4db07e92-f3e1-11e2-8911-df9700e008cd.png)

**Comment by janjongboom** [comment]
@nightwing @fjakobs is this in the plans?

**Comment by antmorozov** [comment]
There is also a problem with positioning of combining characters after non-ascii symbols.

For example, in the russian word "ударе́ние", the acute sign must be above "e", but in Ace it's above "н".

But "Montréal" looks good (it's not "é", it's "e" + acute), although the cursor is still misplaced. If you replace latin "e" with cyrillic "е", the acute jumps to next "a".

![image](https://cloud.githubusercontent.com/assets/169770/11163602/aa48a514-8ae6-11e5-8cd7-6eb8a0ae4bab.png)

Is there any chance it could be fixed? The issue is almost 2.5 years old.

**Comment by antmorozov** [comment]
> There is also a problem with positioning of combining characters after non-ascii symbols.

> For example, in the russian word "ударе́ние", the acute sign must be above "e", but in Ace it's above "н".

> But "Montréal" looks good (it's not "é", it's "e" + acute), although the cursor is still misplaced. If you replace latin "e" with cyrillic "е", the acute jumps to next "a".

> Is there any chance it could be fixed? The issue is almost 2.5 years old.

Opps, looks like it's "Ubuntu Mono" font issue. Sorry.

**Comment by stefanocoretta** [comment]
Any news on this?
