### ISSUE TITLE
Ctrl-P was unable to move the cursor up?

### ISSUE THREAD

**Issue by longgeek** [ajaxorg/ace#2286]
In the mac system, using chrome in the ace-builds project in editor.html editor, Ctrl-P cannot be used to move the cursor up?
How to do?
How to let it do not go to the matching bracket？

**Comment by trss** [comment]
I feel that this issue is still valid. The Default Keyboard Shortcuts at https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts says that "Up, Ctrl-P" is for "Go line up" on Mac. It's either an issue in the behavior or in the Wiki.

Also, `editor.commands.bindKey({"mac": "Ctrl-P"}, "golineup")` is a better way to provide the workaround as the shortcut will kick in only on Mac's.

**Comment by marcinkaszynski** [comment]
I would second what @trss wrote above.  I know this doesn't sound like a big deal, and I can (and will) override it in my apps, but to someone used to the emacs-y key navigation (which is supported by virtually everything that accepts text input on osx) this makes things awkward.  And making it default means that many web developers won't even know that their site breaks the principle of least astonishment for some users.

For something this basic, cross-app consistency on my system should have higher priority than cross-system consistency of one app.

I would send a patch, but I noticed this was intentional (#2007), so I'll just vote to please reconsider. :)

(thanks for the awesome editor, btw!)
