### ISSUE TITLE
Alt + Delete doesn't delete previous space + previous word, but instead only deletes previous space

### ISSUE THREAD

**Issue by x-ji** [ajaxorg/ace#2296]
I have to press it twice to delete a word. Quite inconvenient.

**Comment by nightwing** [comment]
Do you want it to delete previous space only in case if there is one space or for multiple spaces too?
Deleting in case of only one space was disabled some time ago since it was leading to inconsistent behavior for multiple selections.

**Comment by AnonJ** [comment]
I'm not sure that's what I meant... The issue is that when I press Alt + delete, I should delete the previous *word* together with the previous space. e.g. if I have something like "foo bar", then when my cursor is at the position before "b", and I press Alt + delete, the space before b, *as well as the word "foo"*, should be gone. Now only the space is gone but not the word "foo". Probably I didn't paraphrase my question clearly...

**Comment by nightwing** [comment]
Do you expect `foo` to be deleted if there is more than one space between these words?
something like
 ```
foo      |bar
```

**Comment by AnonJ** [comment]
It's actually both fine. I think in Sublime the default behavior is not to delete and in Eclipse it's to delete. However I would say that's a rare use case which I wouldn't care a lot. Whichever is easier to implement/set/maintain etc., I'll go with that. What I encounter 90% of time is being unable to delete the word with only one space, which impacts efficiency significantly.
