### ISSUE TITLE
Embedded HTML / XML highlighting in Markdown mode could be refined

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2329]
I couldn't see if this was documented / exported anywhere, but it seems rather surprising to me.

Repro:
1. Open Kitchen sink,
2. Set HTML mode,
3. Type `<10 '` on the first line,
4. Inspect the current state with `editor.session.bgTokenizer.getState(0)` in a JS console.

I see:

```
["string.attribute-value.xml", "tag_stuff"]
```

Is it permissible for there to be multiple states attached to a line? Is this documented somewhere? It would be useful to have this better documented here if so: http://ace.c9.io/#nav=api&api=background_tokenizer

This does seem unlikely however -- a number of places attempt to check the current state, with e.g. `state === ...`, and this will fail if multiple states are returned.

**Comment by kevinushey** [comment]
Just to provide some motivation -- the reason why this is an issue, someone might write, in a Markdown document,

    There are <100 apples in the tree.

The `<100` is seen as the start of an XML tag; really, it should be seen as just a plain `<`.

Note that Markdown only permits HTML within its own 'blocks', e.g. from http://daringfireball.net/projects/markdown/syntax:

> The only restrictions are that block-level HTML elements — e.g. <div>, <table>, <pre>, <p>, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) <p> tags around HTML block-level tags.

**Comment by nightwing** [comment]
where is `state ===` checked? That must be a bug

At the start state could only be a string, but that couldn't handle things like string interpolation, so we have added support for stack of states. 
This allows to have rules like
```js
nestableComment: [{
   regex: "\\(\\*", token: "nested.comment.start", push: "nestableComment"
}, {
   regex: "\\*\\)", token: "nested.comment.start", next: "pop"
}, {
   defaultToken: "nested.comment"
}]
```

In the future this system can change to something described in https://github.com/ajaxorg/ace/issues/1227#issuecomment-66869175  

> The <100 is seen as the start of an XML tag; really, it should be seen as just a plain <.

Markdown is quite tricky to highlight since it doesn't have a well defined spec.
Ace highlights html tags in markdown same way as sublime  
Also when i write 

```
There are <100 apples in the tree. And >100 in the basket
```

Github shows: There are <100 apples in the tree. And >100 in the basket

And for `stuff <div>in tag</div>` it shows: stuff <div>in tag</div>

So always escaping `<` as `\<` might be a good idea anyway

> Just to provide some motivation -- the reason why this is an issue,

i do not quite understand how markdown issue is connected with getState, could you explain a bit more

**Comment by kevinushey** [comment]
I think a 'fix' here (if so desired?) would be to only allow the HTML / XML highlight rules to kick in inside of the `allowBlock` rule, although I am unsure how exactly that would be handled. Eg in:

https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/markdown_highlight_rules.js#L136-L140

Would it be possible to somehow only allow HTML / XML highlight rules to kick in when encountered in that state?

Sorry, the `multiple states` bit was somewhat of a misnomer; I think that is a separate issue and I'll post it there to qualify what I mean.
