### ISSUE TITLE
Ace won't attach to an element #ace_editor

### ISSUE THREAD

**Issue by adrian7** [ajaxorg/ace#2341]
According to this fiddle http://jsfiddle.net/yDscY/119/ , ACE won't attach to an element with id of "ace_editor". However it will attach to say "ace_editor2"

**Comment by nightwing** [comment]
this happens because [importCssString](https://github.com/ajaxorg/ace/blob/v1.1.8/lib/ace/lib/dom.js#L122) called from https://github.com/ajaxorg/ace/blob/v1.1.8/lib/ace/virtual_renderer.js#L49  creates element with ace_editor id, probably it would be better to change that to something not as easy to type.

**Comment by adrian7** [comment]
It took me some time to get my head around it; maybe worth add it in the docs as a reserved id.
