### ISSUE TITLE
showInvisibles: true AND setUseWrapMode (true)

### ISSUE THREAD

**Issue by peter0123** [ajaxorg/ace#2363]
i test ace in jquery mobile ;)
windows width=360

i used wrapmode and setoptions: showinvisbile..

i think wrapmode overlooks the invisible and i see often not all chars (right side) in editor.

**Comment by nightwing** [comment]
Not taking into account invisible character at the line end is somewhat intentional since usually lines do not end exactly at the last  character and reserving a space for it won't look good https://github.com/ajaxorg/ace/issues/993

> I see often not all chars (right side) in editor 

does this happen for characters other than invisible line end character? if yes do you use maxLines option enabled or not (related issue https://github.com/ajaxorg/ace/issues/2361)
