### ISSUE TITLE
XSS Security Vulnerability with Implementation of HTML5 Messaging postMessage()

### ISSUE THREAD

**Issue by Brian357** [ajaxorg/ace#2393]
Source:
https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/event.js  (line 349)
note: this is one of several files / locations where noticed. Other files include: jshint.js, worker.js, workder_client.js, workder_sourcemint.js. 

Function:
Window.postMessage(message, targetOrigin, [transfer]);

Description:
TargetOrigin parameter for HTML5 Messaging feature postMessage using a wildcard (*) in several locations such as in ace\lib\events.js which allows the potential for cross site scripting attacks from unauthorized sources.  

Remediation:
It is suggested by the OWASP CRV2 regarding HTML5 Messaging to explicitly specify the intended target origin and to not use an open end-point / wildcard (*). 

References:
http://www.w3.org/TR/webmessaging/ 
https://www.owasp.org/index.php/CRV2_ClientSideCodeHTML5

**Comment by nightwing** [comment]
The one in [event.js](https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/event.js) can not be used for xss, since it doesn't post any content. It sends empty message and calls callback when the event is received.

workder_sourcemint is an old file, it is not included in the master.
jshint doesn't use postMessage
worker and worker_client use `worker.postMessage` method which is [different](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage)

**Comment by nightwing** [comment]
Closing, but if you think i am wrong, and there is xss vulnerability, please comment.
