### ISSUE TITLE
Transforms interfere with font metrics, input handling

### ISSUE THREAD

**Issue by stuartpb** [ajaxorg/ace#2406]
Right now, UI element sizes are specified in `px` based on clientRect measurements on the element. These measurements don't take into account the possibility that the values returned by clientRect functions may not be the same size as `px` units in the node's space

If the font measurer is replaced with a non-transformed measurer per https://github.com/ajaxorg/ace/issues/2153#issuecomment-57048027, the misfit element problem goes away, but the input functions are no longer aware of the text size, so caret positioning on click is mis-scaled.

Perhaps a fix would be to have FontMeasurer transform the results from measuring the text by the results for measuring a `1px` element: if the 1px element is 5px tall, it scales its font measurements down by 5. Granted, this isn't a perfect solution (it doesn't directly account for transforms involving perspective or rotation), but it should work around issues with scale (until a better solution, perhaps using the techniques mentioned in https://gist.github.com/Yaffle/1145197, arises).

**Comment by stuartpb** [comment]
I would also suggest specifying UI sizes in `em` and `ch` rather than measuring the text sizes and setting them in `px` via JS.

**Comment by nightwing** [comment]
Measuring text sizes is needed for positioning cursor and selection, it seems to me that using em and ch won't help with that.
I like the idea with 1px element it could improve https://github.com/ajaxorg/ace/pull/1859 which works only for chrome.
However i think this shouldn't be enabled by default, since having editor in the transformed node is rare, and we shouldn't make common case slower for that.

>  but the input functions are no longer aware of the text size, so caret positioning on click is mis-scaled.

when replacing you should use similar classname to get same css rules applied to measurer node and editor container.
