### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by David263** [ajaxorg/ace#2503]
The various inducements on the Web for Ace all ask that I try it out. Okay, I tried it out and it did nothing but display typical Javascript text. I had no idea what keystrokes it supported, or what key would show Help, if indeed it has any Help. In contrast, Emacs is built with help for each large and tiny part of it. The Ace developers are apparently a new breed of engineer who believe one must read all the code to understand how to use a product. Ridiculous.

Ace seems to have no manual, and the only tutuorial I can find shows how to extend it (in Javascript), and how to embed it in a web page, not how to use it. Does it even have a keyboard and mouse interface?

Ace seems to be an attempt to make a programmer's editor, as it has Snippets and autocompletion, which are useful features. But neither one of them works--there is no documentation that I can find that explains what keystrokes invoke them.

I did find a list of a few keyboard shortcuts, but the first one I tried was Ctrl+n, which is the Firefox command to create a new browser window. The next one I tried was also a Firefox command. Ridiculous.

Is Ace a toy or a really useful product? It is impossible to tell. This is the worst-documented product I have seen in recent memory.Is documentation so hard to write for today's modern engineers? Wow.

**Comment by basarat** [comment]
You might find a type information provider extremely helpful : https://github.com/borisyankov/DefinitelyTyped/blob/master/ace/ace.d.ts

**Comment by David263** [comment]
Nope, not helpful at all. Since when is source code acceptable as documentation? What company does that?

**Comment by basarat** [comment]
I wasn't supporting the lack of documentation. Just wanted to share one way out of thiis major difficulty.

**Comment by MysterAitch** [comment]
+1 from me. 

Even now (nearly two years after the opening of this issue) I'm finding myself looking for answers by reverse engineering the source code rather than looking at documentation or examples for anything beyond "plug it in and point it at a textarea".

Having persevered for a while it seems Ace Editor is powerful with a lot of potential (despite having only scratched the surface!) and additional documentation would certainly be a good thing.

**Comment by ryancat** [comment]
Recently I've been working on a project using ace editor and the autocomplete feature. I wrote my custom mode, autocomplete rules, custom behaviours while inserting, as well as some style overwrites. Since there is not many documentation, I ended up with googling many stackoverflow Q&A as well as reading source code to get my work done. I started writing demo on codepen at https://codepen.io/ryancat/pen/mMyvpx

Wish I could send pull requests to the wiki page to better document the findings...

**Comment by geometryzen** [comment]
In the modern world of open source (and not shrink-wrapped, proprietary,
pay-for) software, it's an empirical fact that documentation tends to be
less complete and the source code is often the final source of truth. The
community also tends to work best when people are respectful of the effort
that has been put in on behalf of others, especially when their
contributions have been voluntary.

ACE, IMHO, is somewhere in the middle ground, and I give great credit to
the authors for making it approachable for me.

Here's how I would like to do my part. I have, over the last several years
ported ACE to TypeScript in order to help me understand the code and make
it safer for me to work with. The code is now open source and used in
https://www.stemcstudio.com. Anyone is free to view the source in the
geometryzen/stemcstudio repo.

I have taken the approach (for convenience) of embedding the code in the
product, but I know it could be pulled out into libraries (I had it that
way at one time).

Please feel free to contact me, david.geo.holmes@gmail.com, if I can be of
assistance to this great project.

David

**Comment by David263** [comment]
I think this Issue should remain open, because I still don't understand if Ace is meant to be a supported product or a toy.

**Comment by andrewnester** [comment]
> Ace seems to have no manual, and the only tutuorial I can find shows how to extend it (in Javascript), and how to embed it in a web page, not how to use it. Does it even have a keyboard and mouse interface?

Feel free to use this hosted demo page to explore all the features we have
https://ace.c9.io/build/kitchen-sink.html

> Is Ace meant just for developers?

Ace is not an end product by itself, it's a library which other developers use to build code editors, for example AWS Cloud9 and others. So our primary focus is on developers.

> This is the worst-documented product I have seen in recent memory.Is documentation so hard to write for today's modern engineers?

Sorry to hear that, we try our best to document how to integrate Ace and build the products on top of it. If you have a concrete suggestion on missing sections on how to improve documentation, feel free to raise a separate issues on GH for this. So far this issue is too broad for us to act on. Thank you!
