### ISSUE TITLE
How to make new version of JSHINT work with ACE using require.js?

### ISSUE THREAD

**Issue by n9** [ajaxorg/ace#2556]
I've updated a JSHINT in lib/ace/mode/javascript/jshint.js to version 2.8.0. However, ace via require.js fails to load the JSHINT: `Object doesn't support property or method 'each'` [(jshint.js:15363,1)](https://github.com/jshint/jshint/blob/2.8.0/dist/jshint.js#L15363).

It seems to me that when JSHINT is loaded using require.js, browserified lodash module is not properly loaded in JSHINT.

**Comment by nightwing** [comment]
I am not sure yet. that error and significantly larger size are the reasons why jshint have not been updated so far.

**Comment by n9** [comment]
What version of JSHINT is currently used in ACE? (It was modified 3 months ago, however it does not look like a dist file from that time.) How it was build?

**Comment by nightwing** [comment]
It is done by https://github.com/ajaxorg/ace/blob/master/tool/update_deps.js#L85-L102
last time it was built from  https://github.com/ajaxorg/jshint/tree/ace

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/2561 uses version with underscore instead of broken lodash.

**Comment by nightwing** [comment]
Version with lodash doesn't work because of global `define` with `amd` property, using derequire helps, but lodash is too large anyway, so i think we should keep using undescore like #2561 does
hopefully jshint will switch back to underscore https://github.com/jshint/jshint/issues/2330 or find a way to include only 2-3 functions they actually use.

**Comment by n9** [comment]
Ok, thank you for the update.

**Comment by Martii** [comment]
@nightwing 
Any news on this since it's been a few years? We're running into some questions development side regarding which JSHint is in [*ace-builds*](https://github.com/ajaxorg/ace-builds/tree/master/src) and whether 2.10.2 will be seen in Ace at some point. I'm just barely grasping the build cycle here on this so go easy please. :)

Ref:
* https://github.com/ajaxorg/ace/commits/master/lib/ace/mode/javascript/jshint.js *(History of jshint [last tool'ed update](https://github.com/ajaxorg/ace/blob/c50e196269f7cc84edd8197676a1c22155d2e6a8/tool/update_deps.js#L93-L110) with a [last update of 2015 09 29](https://github.com/ajaxorg/ace/commit/a35ba7cb524eedca933d180c9b53dfce276541c1#diff-5bf1b70545682d97176a8c4438f9cc2e))*
* https://github.com/jshint/jshint/releases/tag/2.9.0 *(which is about that time period but so is [2.8.0](https://github.com/jshint/jshint/releases/tag/2.8.0) with a much fuller release explanation)*

Thanks for any intel provided.
