### ISSUE TITLE
Python 3 highlighting and library autocompletion not present

### ISSUE THREAD

**Issue by positron96** [ajaxorg/ace#2773]
I use cloud 9 ide to edit python 3 files. I set file type to "Python" in editor.
When I `from urllib.request import urlopen`, editor shows an error on that line, since it thinks it's python 2 which has its old layout for this library. Same goes to other python 3 changes, e.g. `print "abc"` is not shown as error.
Please consider adding "Python 3" item in file types menu with respective highlighting and library scanning.

**Comment by anowlcalledjosh** [comment]
This is especially an issue for `print()`; Ace currently sees the following as a syntax error, even though it's perfectly valid Python 3.

```python3
print("Ni!", end="")
```

**Comment by nightwing** [comment]
Cloud9 uses pylint to display syntax errors, and it displays errors for the version of python with which it runs. Currently it uses the default python version. How do you normally run your app with python 3? 
Python 3 filetype might not work well, since there is no automatic way to detect version and user will have to manually switch type of every file.
One possible solution is to introduce project setting for pylint path, which would change the linter for all files in the project.

**Comment by anowlcalledjosh** [comment]
Checking for a shebang containing `python3` would work fairly well IMHO, i.e. the first line of the file matching `/#!.*python3/`.

**Comment by nightwing** [comment]
@anowlcalledjosh is this shebang commonly added to all python3 files or only to files that are meant to be executable?

**Comment by anowlcalledjosh** [comment]
@nightwing I just add it (`#!/usr/bin/env python3`) to all my Python files (what's the point of Python if you can't execute it?), but I see that it may not be used by everyone. Still probably better than having to manually select py3 syntax highlighting for every file IMO.

**Comment by positron96** [comment]
Ace (or python) requires encoding comment to interpret non-ascii bytes in source files (something like this: ````# -*- coding: utf8 -*-````). Maybe the same could be used for python version. Parsing for shebang is probably a better solution.
