### ISSUE TITLE
No way to match 'change' events to actions

### ISSUE THREAD

**Issue by orens** [ajaxorg/ace#2856]
When changing the contents of the editor through setValue, at least two events are emitted (possibly more). However, there is no way to understand from the event handler what was the action triggering the event.
Suppose, for instance, you want to do something after every change made to the document by the user, on setValue you get two events (or more) some time after the call to setValue is completed, and they are tagged as 'remove' and 'insert'.

Please add some information about the trigger (at least if it is API or user edits)

**Comment by nightwing** [comment]
change events are emitted during setValue call not after it. It is possible to check `editor.curOp.command` to see which command was invoked. For all the changes done via user interface (except drag and drop) `editor.curOp.command.name` will be the name of the command. For other changes it will be `undefined`.

```js
editor.on("change", function(e) {
    console.log(editor.curOp)
})
```

Note that triggering a change from change event might not work well, since other change listeners will get events in the wrong order.

**Comment by orens** [comment]
@nightwing , thank you for the response!
I wasn't aware of the curOp field.
It sounds like it is what I needed.
I will test it and update here.

**Comment by orens** [comment]
Works like a charm :+1:  Thanks!
