### ISSUE TITLE
Is there a way to disable auto-indent?

### ISSUE THREAD

**Issue by zhanzhenzhen** [ajaxorg/ace#2895]
Is there a way to disable auto-indent?

**Comment by nightwing** [comment]
You can do something like https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/plain_text.js#L48-L50

**Comment by zhanzhenzhen** [comment]
Thanks. so, only Mode can control the auto-indent? Does the Ace API provide an option to enable or disable auto-indent for all modes?

Another question is that does the API provide some function of removing trailing whitespaces (that may be caused by auto-indent)?

**Comment by nightwing** [comment]
For now only mode can control autoindent. An option to control autoindent for all modes can be added at https://github.com/ajaxorg/ace/blob/master/lib/ace/editor.js#L961.

Why do you want to disable autoindent? Is it broken for some modes?

There is a trimTrailingSpace method, in whitespace addon https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/whitespace.js#L120, which removes all trailing spaces.

**Comment by zhanzhenzhen** [comment]
no no, not broken. Just because auto-indent may add unnecessary whitespaces, I always disable auto-indent in all editors (Sublime Text, Atom, etc.) I know people like me are very few nowadays.

**Comment by nightwing** [comment]
Would you enable it if whitespace was automatically removed when cursor left the autoindented line?

**Comment by zhanzhenzhen** [comment]
Yes, I will enable it if it acts this way, just like what Microsoft Visual Studio does. But most editors don't have this behavior.

**Comment by cubiclesoft** [comment]
@zhanzhenzhen I don't know why you closed this.  Please consider re-opening this issue.  You aren't alone in the desire for this option.  I generally only run editors that can turn auto-indent OFF.  Auto-indenting, automatic quotes/parenthesis/brace/bracket closures, automatic code folding, etc. always end up doing the wrong thing and hinder writing code the way I want.  I want an option to completely disable "helpful" features like these and any editor without the ability to disable the features is broken by design:

@nightwing Automatic changes to any document as a person types is a violation of the relationship I expect with my text editor - _You are modifying what I type without my express permission to do so._  I expect exacting precision:  Each character I type appears, is tracked, and stored as-is.  No more and no less than that.  Not really hard to understand.  Further, I would find automatic removal/adjustment of trailing whitespace that I had entered myself to be exceedingly annoying AND a bug.

Just because a lot of people use features that are _enabled by default_ doesn't make those features right.  The user just get used to them and it becomes part of their normal typing workflow to constantly correct the mistakes that those features create.
