### ISSUE TITLE
Ace scrolls when on focus

### ISSUE THREAD

**Issue by webchaz** [ajaxorg/ace#2963]
We're loading ace within a scrollable modal window and clicking on the ace editor, it scrolls up about 100px.  Any idea how to disable this?

**Comment by tothandras** [comment]
We have the same error, it also scrolls when editing.

**Comment by mike-strauch** [comment]
Seems to be coming from [here](https://github.com/ajaxorg/ace/blob/fc9a2396afa9d091013c46dc73fdc117a87466fd/lib/ace/keyboard/textinput.js#L78-L88).

**Comment by kruny1001** [comment]
+1

**Comment by kruny1001** [comment]
Use version 1.2.3, After replacing thsi version, it doens't scroll up

**Comment by SvenSchoene** [comment]
Even when using 1.2.3 we still have this issue... :(

**Comment by alphatesla** [comment]
stille in error for me on 1.2.6

**Comment by nightwing** [comment]
if you still see this issue with 1.2.6, please show a page where the issue can be reproduced

**Comment by otopsy** [comment]
i've made a PR on this, because it was so annoying #3227

**Comment by lithiumlab** [comment]
I can confirm this is happening only on editor boxes that are in the lower part of a large page.

**Comment by nightwing** [comment]
Turns out this is caused by a bug in the behavior of position fixed, which works differently for children of nodes with transforms applied.

#3279 adds a workaround for that, but it needs some more work before it can be merged https://rawgit.com/ajaxorg/ace/scroll-bug/demo/scrollable-page.html

until this is fixed in the next version, please add
```
.ace_text-input {position:absolute!important}
```
somewhere in your css as a workaround.

merging this into https://github.com/ajaxorg/ace/issues/3245 since it had a better description of the issue

**Comment by lithiumlab** [comment]
Great, thanks for the timely answer.
