### ISSUE TITLE
Many Android keyboards behave poorly

### ISSUE THREAD

**Issue by edemaine** [ajaxorg/ace#2964]
I just tried the Kitchen Sink on SwiftKey (one of the most popular Android keyboards) and the built-in Samsung keyboard on a Galaxy Note 4 (Android 5.1.1).  They behave very strangely in two different ways:
- SwiftKey: the behavior of typing seems to be that typing any character acts like pressing backspace.  Swiping a word deletes more characters?
- Samsung keyboard: typing some letters and hitting space seems to create the word, but doesn't actually insert a space, so you need to double spaces to get what you want.  Swiping seems to give random gibberish unrelated to the word you swiped...

Is there any hope of fixing this (without requiring users to switch keyboards)?  Or should I just not be using Ace with its hidden input magic on Android?

**Comment by henrikhaugboelle** [comment]
+1

**Comment by Miha-x64** [comment]
[Issue with backspace](https://github.com/ajaxorg/ace/issues/1917) can be merged here.

**Comment by Bahanix** [comment]
Same problem on two phones (Xperia Z1 Compact and Galaxy J5) using Android 5.1.1 with SwiftKey.

**Comment by Miha-x64** [comment]
I don't think it is going to be fixed. This issue is two months old, and [the other one](https://github.com/ajaxorg/ace/issues/1917) is two years old.

**Comment by NesooseN** [comment]
This editor is now part of cPanel, file editor do not work very well, in my example it is really bad on xperia z4 tablet.

- Can not copy,cut,past,select anything
- Typing, deleting is strange, sometime deletes words etc.

Please fix this.

**Comment by funerr** [comment]
Any solution yet for the swift keyboard ("backspace problem")?

**Comment by PzYon** [comment]
I have similar issues on my OnePlus 5T (Android) with Chrome and Swiftkey. When using the default keyboard it seems to work fine.

For example when I type `console.log` it resuts in `cnoee.lg`. Don't quite understand the behavior, but it seems that every second character replaces the previous one... Below is the sequence. On the left is the pressed key, on the right is current value of the editor:
- c: `c`
- o: `co`
- n: `cn`
- s: `cns`
- o: `cno`
- l: `cnol`
- e: `cnoe`

Will this be fixed sometime? It's a pity as it makes using Ace an Android with Swiftkey very tedious if not impossible. Even though I really like Ace im considering using an other editor due to these problems...
