### ISSUE TITLE
The markdown folding doesn't work consistently for "#" and "="

### ISSUE THREAD

**Issue by academyofzhuang** [ajaxorg/ace#2973]
The markdown folding doesn't work consistently for "#" and "="

``` markdown
# article 1
A Paragraph.
## level 2
A Paragraph.

# article 2
A Paragraph.
```

When I click the fold icon at the left of article one, I expect it to fold all lines till article 2. Current behavior is to fold all lines till level 2.

However, this works as expected.

``` markdown
article 1
======
A Paragraph.
level 2
--------
A Paragraph.

article 2
======
A Paragraph.

```

**Comment by stefanvollmar** [comment]
Congratulations for an extremely useful package - thank you!

However, I have also observed the behaviour described in #2973 - it is very unfortunate because for our use case it really degrades the user experience of an otherwise excellent tool. 

I can add that:
```
# heading 1
## heading 2
something
### heading 3
#### heading4
other
```
will display folding icons at headings 1, 3 and 4 which do nothing at all. I might try to fix this myself if given some pointers. Many thanks in advance!

**Comment by nightwing** [comment]
Thanks for suggestion of help, and for poking this issue.
Turned out it was very easy to fix  https://github.com/ajaxorg/ace/pull/3841

**Comment by stefanvollmar** [comment]
Excellent - thank you very much!
