### ISSUE TITLE
How to add code Folding in ace editor manually

### ISSUE THREAD

**Issue by vinothwindows47** [ajaxorg/ace#3019]

**Comment by GitTom** [comment]
do you mean 'how do you add a fold point' manually?

I think the official and best answer is to use 'region' blocks (documented [here)](https://github.com/ajaxorg/ace/wiki/Non-Standard-Code-Folding):

//#region [optional description]
     [code that will be folded here]
//#endregion 

One reason this is good is because it works in other editors - can't remember for sure, but either Eclipse or IntelliJ support it for starters.

But I've also found that it works with braces even within a comment, so you could just do

// [optional description] { 
     [code that will be folded here]
// }
