### ISSUE TITLE
Cursor skipping ahead

### ISSUE THREAD

**Issue by vmarasow** [ajaxorg/ace#3032]
I'm having a weird issue with the editor, any time I type fi into the editor the cursor jumps ahead one space, what ends up happening is I have my cursor ahead of where the text is being inserted.
I tested it on the editor in the live demo and the issue is there too.
I'm using it for JavaScript BTW.

**Comment by nightwing** [comment]
this can happen when using non-monospace font, or when fi is rendered as one character due to ligatures.
Could you tell me a bit more detail about the issue: 
- Which browser/OS do you use?
- On which site do you see the issue?
- Do you see the same issue on https://ace.c9.io?

**Comment by vmarasow** [comment]
Chrome on Windows 10 (Not insider build).
We are using skuid a salesforce app that uses it, that's the main place where I have the issue, I successfully duplicated the issue on your demo page as well as ace.c9.io

**Comment by nightwing** [comment]
Unfortunately i couldn't reproduce the issue with windows 10 vm
Could you give me a screenshot demonstrating the issue, maybe that would help to see what's going on.
Also try adding 

```css
* {
    font-variant-ligatures: no-common-ligatures;
}
```
rule using browser devtools.

**Comment by mshou** [comment]
Hello, 
I'm having the same issue using Windows 7 64bits, with Chome 56.x and Firefox 52.x
In IE 11 its ok.

screenshot's on https://ace.c9.io with chrome:

i just wrote find (there's no space after the word)
![image](https://cloud.githubusercontent.com/assets/15908034/24449173/81a5509a-146e-11e7-8670-9636ccc5fe9d.png)

if u just wrote fi :
![image](https://cloud.githubusercontent.com/assets/15908034/24449863/919391b8-1470-11e7-9e98-34a4639651d8.png)

the cursor is after "d", i wrote an 'x' and it shows before 'd'
![image](https://cloud.githubusercontent.com/assets/15908034/24449963/fb0d34f0-1470-11e7-97ea-fcc540418584.png)

I copied and paste 'find' and it shows fin
![image](https://cloud.githubusercontent.com/assets/15908034/24450084/675c3fa2-1471-11e7-95ad-95ee9a0d0237.png)

this rule solve the problem !
* {
    font-variant-ligatures: no-common-ligatures;
}

Regards

**Comment by a3n** [comment]
Hello,
I am having the same issue using Arch Linux, with Firefox 70/71 and Chromium, with Wayland and X.
This bug probably appears on a variety of setups.

To create a minimal reproductible example with Firefox, the Nimbus Mono PS font can be used as the browser default monospaced font. It is part of the `gsfonts` package.
The problem seems to be due to two things:
- there are ligatures in this font that probably should not be there (at least `ff`, `fi`, `fl`, `ffi`, `ffl`), as it breaks the fixed-width property ;
- (probably) the `getCursorPosition` function does not take such cases into account, reasonably assuming monospaced fonts strictly respect fixed-width property.

In buggy cases, the cursor appears to be where it would be if there were no ligatures, leading to a situation in which typed letters do not appear just behind the cursor.
This bug appears if there is a ligature (`ff`, `fi`, `fl`, `ffi`, `ffl`) before where the cursor should be on the same line. 

Applying the rule
```
.ace_content  {
	font-variant-ligatures: no-common-ligatures;
}
```
solves the problem, preventing it from happening with other "non-strict" monospaced fonts.
