### ISSUE TITLE
Search bar color issue

### ISSUE THREAD

**Issue by kgrammer** [ajaxorg/ace#3071]
I've updated to ACE 1.2.5 and I'm having an issue where the search box for all of the dark themes is light and light color (close to or the same color) and you can't see the search text when entered.

I searched here and haven't seen anyone else report this problem, so it may be something strange we are doing here.  

I can replicate the issue here my picking any of the dark themes and pressing Ctrl+f and I will get a search bar with a white background and white text.

Any thoughts?  Is this a known issue with Ace 1.2.5?

**Comment by nightwing** [comment]
Most likely this is caused by a conflict with other styles on your page, since it doesn't happen on ace.c9.io
From which version did you update?

**Comment by kgrammer** [comment]
I honestly don't know the version.  The minified version of ace.js doesn't include the version.

So the prior version had a black background with white text for the search bar.  The search bar layout is different and is now white on white (though some seem to have a very light (almost white) text on white, so you can ALMOST see letters.  I can't see a path to conflicts with other styles.  This just looks like a change in the Ace search bar colors for 1.2.5.

**Comment by nightwing** [comment]
There is `ace.version` property since 1.2.2
Could you share the page where you see the issue, or maybe create a demo page.
> I can't see a path to conflicts with other styles.

with css there is always a path for conflicts:)

**Comment by ratiotile** [comment]
I am experiencing the same issue with ace v1.2.3 (brace 0.8.0) on the `twilight` theme.
![ace search text color](https://cloud.githubusercontent.com/assets/7064626/18065815/8f5713ca-6e03-11e6-9696-248986570233.PNG)
![ace search text color highlighted](https://cloud.githubusercontent.com/assets/7064626/18065817/9124a5c8-6e03-11e6-8450-3851bd205f48.PNG)

Is there a way to programmatically set the color/theme for the searchbox? I am using React so I want to avoid having to add a .css file.

**Comment by nightwing** [comment]
@ratiotile you could use `require("ace/lib/dom").importCssString` similar to https://github.com/ajaxorg/ace/blob/v1.2.5/lib/ace/autocomplete/popup.js#L303-L306.
Could you check if this is caused by a global rule doing `input{color:inherit}` ?If yes then https://github.com/ajaxorg/ace/pull/3076 should fix the issue.

**Comment by ratiotile** [comment]
How do I do `require("ace/lib/dom")` when using brace?

**Comment by ratiotile** [comment]
solution:

    window.ace.acequire('ace/lib/dom').importCssString(".ace_search_field{color: black}")

**Comment by kratsg** [comment]
Hi all,

I've traced this issue actually to two different libraries that a lot of people might use:

- bootstrap.css
- normalize.css

Both of them set a `color: inherit` onto the buttons and textboxes involved as part of normalizing css. In which case the dark theme (such as twilight), still needs to set the color because it's just inheriting from the theme (which sets the color to white). It's an ill-defined css for the theme in my opinion.

**Comment by daniely** [comment]
I also had to update `.ace_replace_form`
