### ISSUE TITLE
Thai language problem

### ISSUE THREAD

**Issue by ahmed-a-e2006** [ajaxorg/ace#3141]
There is a problem with cursor in thai language
if you put the following characters, the cursor position would be wrong. try to put the cursor ate the end of the lines, or put anywhere and press enter you will find the splitted text in the new line begins from cursor position before the actual position that you pressed the enter key at

คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง. คุณเป็นอย่างไร. เป็นอย่างไรบ้าง.

**Comment by chenkehxx** [comment]
maybe you can try it on other browser not chrome, I have the similar problem about chinese language input. it works well in safari, but not chrome.

**Comment by jperasmus** [comment]
I've tested this, and the problem is the same in Safari and Firefox as well. Here is an example of how it works in English but not Thai.

![ace-thai-problem](https://user-images.githubusercontent.com/6787452/35259712-f9164c00-000f-11e8-9616-0fe2ee2a442d.gif)

The problem is probably not specific to Thai, but any language with characters that have a character `length` of more than one.

<img width="172" alt="thai-character-length" src="https://user-images.githubusercontent.com/6787452/35259724-0e1a1eba-0010-11e8-84b5-3822e8c6388d.png">

**Comment by thammawat-s** [comment]
This bug is still there.  I test on Windows 10 (Chrome + Firefox ), and IPAD (Chrome)

![cursor](https://user-images.githubusercontent.com/75549627/122402470-b5b5a300-cfa7-11eb-8625-d6d0a6510924.PNG)

**Comment by andrewnester** [comment]
This relates to this issue, so closing as a duplicate https://github.com/ajaxorg/ace/issues/460
