### ISSUE TITLE
How to use different DOM elements

### ISSUE THREAD

**Issue by burakkaptan** [ajaxorg/ace#3156]
Hello, 

I use the editor with div tag. However it doesn't work with textarea, input etc. What should i do to use editor with textarea?  There is an example below:

It works like this way:
`<div id="editor">...</div>`

However it doesn't work when i try these: 
`<input type="text" name="" id="editor">`
`<textarea name="" id="editor" cols="30" rows="10"></textarea>`

**Comment by nightwing** [comment]
It works see http://jsbin.com/yaqesaxudo/edit?html,output.
But why do you want to use textarea instead of div?

**Comment by burakkaptan** [comment]
Thanks for the reply. I was using #editor id instead of .ace_editor class for styling. Now i use .ace_editor class and the issue was solved. 
I'd like to use textarea because i try to build some kind of WP plugin. The plugin purpose; users put their custom CSS code into form and submit those codes to database. However i encountered another issue now. When i submit code, the form doesn't save values with Ace Editor. Form works well without Ace Editor. I don't know what the problem is. What shall i do now? 

Thanks again for your time.

**Comment by nightwing** [comment]
use ace editor in a div tag
add a " submit" event listener to the form, and when it is called create a hidden textarea, and do textarea.value = editor.getValue()

**Comment by rocketinventor** [comment]
@nightwing What would that JS Bin look like with a theme (i.e. Ambience) on it?

**Comment by burakkaptan** [comment]
i get the value with "editor.getValue", then i try to put this value back to editor. Everything works well so far. However when i put the value back to editor, editor returns the value with plain text not as code. I have also tried some jquery and javascript code like outerHTML but no luck. Screenshot was enclosed:

![plain](https://cloud.githubusercontent.com/assets/6393475/20959737/981da0ce-bc6d-11e6-87f0-b8ce7a2e1190.png)

**Comment by rocketinventor** [comment]
@burakkaptan What code are you using to enable syntax highlighting? The code sample that @nightwing  posted does not have any syntax highlighting, or theming, even though it claims to.

**Comment by rocketinventor** [comment]
@burakkaptan In the are where you put the JS code, try adding this line: `editor.session.setMode("ace/mode/javascript")`.
Here is an updated version of @nightwing's JSBin (which did _not_ have this feature, originally): http://jsbin.com/vejebeb/edit?html,output

**Comment by rocketinventor** [comment]
@burakkaptan Also, make sure that you are using `editor.setValue` when trying to set the text to display inside of ace. Jquery, `.innerHTML`, `.outerHTML`, and `.value` are not going to help you much here because that is not the way Ace works.

**Comment by burakkaptan** [comment]
Here is Ace my code: 
`var editor = ace.edit("editor");`
	  `  editor.setTheme("ace/theme/merbivore");`
	   ` var cssmode = ace.require("ace/mode/css").Mode;`
	    `editor.session.setMode(new cssmode());`

If you want, i can upload all of WP plugin to my host and give you login credentials. So maybe you can figure out what's wrong with the code.

**Comment by rocketinventor** [comment]
@burakkaptan What's up with the last two lines? I took a look at them, and most definitely the cause of at least half of the problem you are having.
Instead of:
`var cssmode = ace.require("ace/mode/css").Mode;`
`editor.session.setMode(new cssmode());`
Why not just use `editor.session.setMode("ace/mode/css")`?

Also, make sure to use `editor.getValue()` and `editor.setValue()` for interacting with ace contents by JS. That should solve the other half of your issue.

Check out my updated JSBin using **_your_ CSS code and Ace theme**: http://jsbin.com/zozeva/edit?html,console,output

P.S. I am highly curious as to how you came up with those last two lines, and would love to hear about it. Hopefully, it is a mistake that we can all learn from.
P.P.S. You might find [this documentation](https://ace.c9.io/#nav=howto)  on embedding Ace to be helpful.

**Comment by nightwing** [comment]
@burakkaptan please comment if you still see an issue with this
