### ISSUE TITLE
Weird highlighting in autocomplete popup

### ISSUE THREAD

**Issue by yogitaAP** [ajaxorg/ace#3188]
I have written my own completer and I am supplying an array for the same. However, the highlighting done on the items seems to be little weird or that may be the use case and I am not aware but I need only exact match to be highlighted. For example, if I type getData, I get the matches, so I need only exact matches to be highlighted in the popup. In the screenshot attached here, other substrings which are not a match are also highlighted. I just need to know how is this happening. I can take care of the fix myself. 

<img width="600" alt="screen shot 2017-01-18 at 7 03 10 pm" src="https://cloud.githubusercontent.com/assets/9781726/22065996/ce786ba4-ddb0-11e6-9be7-d60629056b64.png">

**Comment by struhtanov** [comment]
As far as I understand the reason of this bug is poor `matchMask` calculation algorithm that is calculated in [FilteredList](https://github.com/ajaxorg/ace/blob/6bd1b82afa55b26e6bcea98ba5f71e5e52a838fe/lib/ace/autocomplete.js#L480) and later used in [Popup](https://github.com/ajaxorg/ace/blob/6bd1b82afa55b26e6bcea98ba5f71e5e52a838fe/lib/ace/autocomplete/popup.js#L186) for tokenizing and highlighting matched text. It uses bitmask, but Javascript bitwise operator works with 32-bit integers.

So if the text is more than 32 symbols, there will be highlights of random text.

**Comment by ghosthope** [comment]
See this PR: #2996 and #3069

**Comment by yogitaAP** [comment]
Dude thanks for the response! But I scrapped that feature from my project
already. Found a different angle for the product. But thanks. Will look
into the prs. Might be fun for trying it out in side projects.
