### ISSUE TITLE
Improve ace building process

### ISSUE THREAD

**Issue by alisianoi** [ajaxorg/ace#3296]
Hello, thanks for your work on ace!

I would like to point out that right now building ace is not comfortable, let me show you some cases:

Case 1: `git clone git@github.com:ajaxorg/ace`, then I see a `Makefile` and since I am a simple guy, I just type `make clean` because I can. That deletes the `build` directory and `git status` is no longer clean. Not nice.

Case 2: `git clone git@github.com:ajaxorg/ace`, then I do `npm install` followed by `node Makefile.dryice.js`. This builds ace but unfortunately also copies a couple of files into `lib/ace/snippets` directory. This leads to `git status` being not clean again. Also, if you use `node Makefile.dryice.js --path ../some/other/path`, it will still copy new files into `lib/ace/snippets`.

I would like to make it so that building ace does not affect `git` staging area. I was also trying to understand `Makefile.dryice.js` in order to fix it but failed, here is why:

`Makefile.dryice.js` just looks like an ordinary `nodejs` script that has a bunch of functions. If it is run as a script, it calls `main(process.argv)` and builds ace. If it is `required` from somewhere else, it exports the `buildAce` function.

The function that copies things into `lib/ace/snippets` is most likely the `addSnippetsFile` function. It is used in `buildAce`.

Where does `dryice` node module come into play? It looks like the `copy` function comes from some other module called `architect-build`. Does ace even need dryice at all?

I would love to get to the bottom of this and make the build process cleaner. Currently, I suppose that the `ace-build` repository does not suite my needs because I would like to be able to modify ace and immediately build-and-run my version (also creating MRs to upstream when appropriate).

**Comment by nightwing** [comment]
Currently dryice is only used to call uglify-js ([#L575](https://github.com/ajaxorg/ace/blob/master/Makefile.dryice.js#L575)), since architect-build uses uglify-js 2 which is much slower.

The snippet files generated in lib/ace/snippets to not trigger 404 errors for languages which do not have snippets, we probably should add them to git.

The Makefile have not been used for a while, we probably should remove it, but when it worked, i think `make clean` was used to remove build artifacts and `make build` to call `Makefile.dryice.js`
