### ISSUE TITLE
Ace editior doesn't work with framework7.io

### ISSUE THREAD

**Issue by wsngamerz** [ajaxorg/ace#3326]
I am trying to create a mobile ide with ace editior and framework7.io and apache cordova but when I try to use the editor, I cannot type into it. Any help please or a workaround. PS: I am focusing on Android.

**Comment by nightwing** [comment]
Does it not work only on phone or on desktop too? Could you show a page where the issue is reproducible?

**Comment by wsngamerz** [comment]
I haven't had chance to test on PC but i have a video showing what its doing but to be honest, i reckon that its the framework7 framework. A video to show what happens is [Here](https://youtu.be/CMJqtMfEJPI).

**Comment by nightwing** [comment]
This is caused by one of touchstart event listeners added by framework7 to document.
If i remove the listeners using chrome devtools everything works fine.
I couldn't debug this further since the code in the demo was minified, but this is not an issue with ace, try opening an issue for framework7 instead
