### ISSUE TITLE
Failure to remove bracket highlights

### ISSUE THREAD

**Issue by ggoodman** [ajaxorg/ace#3392]
In https://github.com/ajaxorg/ace/blob/7fc511d0d6481378e806c25de87f7f96ca9ecbcb/lib/ace/editor.js#L513-L539 there appears to be a timing issue whereby the async callback will be invoked in a state where `session.$bracketHighlight` holds an existing value. As a result, the previous value is overwritten and zombie `.ace_bracket` markers accumulate over time. I've been able to reproduce this by opening and closing an `Editor` and clicking before and after brackets with a conditional breakpoint set at  https://github.com/ajaxorg/ace/blob/7fc511d0d6481378e806c25de87f7f96ca9ecbcb/lib/ace/editor.js#L537 whose condition is to assert the truthiness of `session.$bracketHighlight`.

**Comment by nightwing** [comment]
This should not happen normally, because this.$highlightPending flag prevents calls to setTimout when bracketHighlight is not null.

But on https://next.plnkr.co same session is attached to several editor instances at once, so every editor calls the setTimeout and overrides session.$bracketHighlight.

Are you creating new editor instance every time the tab is changed?

**Comment by ggoodman** [comment]
Hello @nightwing, yes, I'm creating a new `Editor` instance per 'pane'. In Plunker, it is possible to have multiple panes visible at once so this is necessary.

However, you were absolutely right in your assessment. I was not properly cleaning up when panes are destroyed. For future reference, the solution in my situation was to clean up like this:

```js
// The EditSession's lifecycle is owned by the app so we need to 
// prevent `Editor#destroy` from destroying the `EditSession` as well.
editor.setSession(null);
editor.destroy();
```

Thanks for taking a look!
