### ISSUE TITLE
Feature Request: Colour previews

### ISSUE THREAD

**Issue by coffeeandpixels** [ajaxorg/ace#3394]
Is it possible to have colour previews added to Ace? For example, highlight hex codes in the specified colour.

**Comment by richardtallent** [comment]
Interesting idea! I can't think of a way to do it easily offhand. The Text Highlighter rules allow you to add a span with a CSS *class* to a recognized bit of text (such as a color), but there doesn't appear to be a way to set the *style* attribute of those spans, and with more than 16 million possible colors, using classes alone would be impractical.

Now, let's say any value in the "token" property (or, importantly, returned by a token function), if prefixed with "style:", would go into the rendered token's *style* attribute instead of the class, you could have a rule something like this:

```Javascript
{
    token: function(value) {
        return ["css_color", "style:border-left-color:" + value];
    },
    regex: "#[0-9A-Fa-f]{3,6}"
}
```

with CSS like this:
```CSS
.ace_css_color {
border-left: 1em solid;
}
```

I am basically an ACE novice, I've only implemented a few custom language modes and have no real knowledge of the internals.

That said, I *think* adding custom styles to the spans could be done with a small change to text.js, @ line 361 to recognize "classes" from the token that are actually style directives and handle them accordingly. E.g.:

```Javascript
{
    token: "css_color",
    regex: "#[0-9A-Fa-f]{3,6}",
    style: function(v) { return "border-left-color:" + v; }
}
```

Even easier would be supporting an optional "style" attribute on the rule, which would take a function with the matches (as token can), with the function returning the appropriate style string. While I'm usually not a big fan of style attribute (I'm a "class all the things" guy), I can imagine other situations where this could be very convenient.

Note that I used the border color to show the example, which is a bit wonky I would have used ::before and content to put a block character like ■ and styled it with the color, but inline CSS doesn't allow styling of pseudo-elements. The only way to avoid that would be to override the entire render function for the span to put a literal ■ there with its own inline CSS, but I'm not sure how well that would work with the editor.

**Comment by strawberry-sundae** [comment]
Hi, @richardtallent.

Thank you very much for your thorough and helpful reply. I was absent from Github for quite a long time, and only just saw it.

I’m only familiar with HTML and CSS, but what you’ve written looks logical. Hopefully I will soon have the skills to try this out. Thanks again!

Regards
Ryan

**Comment by davidjb** [comment]
Have there been any changes in ACE since 2017 that would enable this functionality? The docs at cloud9-sdk.readme.io/docs/highlighting-rules doesn't look like it and unfortunately hacks like https://github.com/ajaxorg/ace/issues/3168 don't work - the tokens only extend to the `class` attribute. 

Technically, you _could_ write CSS classes for literally _every_ hex colour and use a function tokenizer to add the hex into the `class`, but that's going to bring your browser to its knees with `2^24` classes 😛

**Comment by davidjb** [comment]
Answering my own question somewhat, but a rather hacky solution is to actually create those aforementioned classes as they're seen:

```js
      {
        token: (value) => {
          // Create a CSS class just for this color
          const colorToken = `color-${value.slice(1)}`;
          let style = window.document.getElementById('ace-colors');
          if (!style) {
            style = document.createElement('style');
            style.id = 'ace-colors';
            document.querySelector('head').appendChild(style);
          }
          if (!style.innerHTML.includes(value)) {
            style.textContent += `.ace_${colorToken} { color: ${value} !important; } `;
          }

          return `constant.other.${colorToken}`;
        },
        regex: '#[0-9A-Fa-f]{3,6}',
      },
```

It needs plenty more work to handle colours that match the background (e.g. white-on-white), and definitely not _the_ solution, but the colours are there:

<img width="185" height="244" alt="Image" src="https://github.com/user-attachments/assets/1cf91b80-e71e-4275-8a35-1e9aa428c44a" />
