### ISSUE TITLE
Feature request: Vim keymap switcher

### ISSUE THREAD

**Issue by marshwiggle** [ajaxorg/ace#3397]
Working in Vim with a keyboard layout that differs from English (say, Russian or Serbian) is not very handy thing to do: every time you have switch from  the "last line" or the "command mode" to the main editor window, you should also change the layout. That's why original Vim editor has it's own layout switcher which can be turn on by the "keymap" command, like this:

:set  keymap=russian-jcukenwin

This switcher is "mode-aware": it turns on the "custom" layout only in the "insert mode". 

Is it possible to implement this feature in ace?

 [Link to original Vim documentation](http://vimdoc.sourceforge.net/htmldoc/russian.html)

**Comment by nightwing** [comment]
Thanks for the issue report, and sorry for a long delay before we got to working on it.

Supporting keymaps the way vim does is harder than it seems because we'll need to manage large number of mapping files and in most places where ace is used switching settings will be hard for users, as the setting won't persist

In  https://github.com/ajaxorg/ace/pull/3557,  i am adding support for using keyCode value from the browser to if non-ascii character is typed in normal mode. 

Could you please try it at https://rawgit.com/ajaxorg/ace/b67400f7c021c53bf66681d15db467333b4fdc31/kitchen-sink.html, and let us know what do you think, are there some cases where this code doesn't work  as well as keymap would?
