### ISSUE TITLE
Support for editorconfig ?

### ISSUE THREAD

**Issue by daamien** [ajaxorg/ace#3510]
Hey !

It would be great if the editor would support the editorconfig files !
http://editorconfig.org/

**Comment by nightwing** [comment]
Do you mean this for ace or cloud9?
Ace is just the ui part and doesn't handle files.

**Comment by daamien** [comment]
yeah I meant for cloud9. Sorry about that,  I thought this was the right place to ask for this.

**Comment by nightwing** [comment]
https://github.com/c9/core and https://community.c9.io/ are good places for reporting cloud9 related issues.
There is already a request for adding editorconfig at https://community.c9.io/t/support-editorconfig/5813/10.

However cloud9 has automatic detection of line endings and indentation, which should cover most of the use cases of editorconfig. Does it not work well, or do you need editorconfig for other features?

**Comment by daamien** [comment]
Global settings are fine but limited. The power of editorconfig is that you can specify different rules for different file types within the same project  : for instance a Makefile can  be indented with tabs, while using space indents for python files. I don't how this can be done with cloud9 at the moment.

**Comment by nightwing** [comment]
Cloud9 sets indentation for makefile to tabs by [default](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/makefile.js#L53), for other files indentation settings are detected automatically, so that almost always it is supposed to do the right thing without configuration.

I don't mean this as an argument in favor of not supporting editorconfig, just want to know if there is a bug in automatic detection, causing wrong settings to be picked in some cases.

**Comment by daamien** [comment]
Ok Makefile was probably a bad example because tab indent is mandatory but there are other situations where there is no "the right thing"  to do. Some projects might want to ident YAML with four spaces, others with two, etc.  And editorconfig provides a nice way to deal with that. That's all.

Thansk for your time
