### ISSUE TITLE
Toggle ace_replace_form using CMD-f no longer available

### ISSUE THREAD

**Issue by vnijs** [ajaxorg/ace#3552]
In version 1.1.8 CMD-f (CTRL-f in Windows) would open search and then toggle the replace form. In 1.2.9 and 1.3.0 CMD-f (CTRL-f in Windows) will hide the replace form if shown but will not show it. Is this intended behavior? If so, is it customizable? I tried using jQuery with keydown but it didn't seem to have any effect. I do see there is CMD-Opt-f (Ctrl-H) but I liked the toggle option better ... and it is already mapped to Spectacle on Mac :)

**Comment by nightwing** [comment]
I liked toggling behavior better too. But many people were complaining about it since they often press the shortcut without looking where the focus is, just to make sure the findbar is focused, and most of other editors do not have the toggling.

You can use the following code to restore toggling behavior
```js
require("ace/ext/searchbox").SearchBox.prototype.$searchBarKb.bindKey( "Ctrl-f|Command-f|Ctrl-H|Command-Option-F", function(sb) {
    var isReplace = sb.isReplace = !sb.isReplace;
    sb.replaceBox.style.display = isReplace ? "" : "none";
    sb[isReplace ? "replaceInput" : "searchInput"].focus();
})
```

In ace-builds version this needs to run after the searchbox extension is loaded.

**Comment by vnijs** [comment]
Excellent! Thank you @nightwing
