### ISSUE TITLE
Editor is not useable and will not render in shadow DOM

### ISSUE THREAD

**Issue by 43081j** [ajaxorg/ace#3590]
Plenty of people are using shadow DOM these days, with the introduction of web components and what not. 

Unfortunately, ace seems to be tied into `document` and makes many assumptions which it shouldn't (such as its owning document, where to query nodes from, etc).

Would it be possible to modernise this a little so ace will detect its shadow root at least rather than assuming `document` is the containing document?

FYI you can quite easily use `Node#getRootNode()` to return the shadow root or `document`.

In places like [this](https://github.com/ajaxorg/ace/blob/fac1081f74afd445c10b72e8097de397b0298d77/lib/ace/virtual_renderer.js#L49) its very important because all the styling is lost at this point due to shadow DOM scoping rules. We should be appending the style nodes to the `head` _only_ when the root node is `document`, otherwise we should append to the shadow root.

---

Example:

```html
<custom-element>
  #shadow-root
    <div class="editor"></div>
</custom-element>
```

Styles and some selectors happen from `document`, so they never reach the contents of the shadow root.

**Comment by nightwing** [comment]
How is shadow dom normally used?

For something like:
```js
var shadow = document.body.attachShadow({mode: 'open'});
editor = ace.edit(null, {maxLines: 2})
shadow.appendChild(editor.container)
```

there does not seem to be a way to automatically detect when new shadow dom is added. 

One way to solve the issue is to add a method `editor.addStylesToShadowRoot()`, which will have to be called every time editor is added to a new shadow root. Would that work for you?

**Comment by 43081j** [comment]
Maybe we could do it on initialisation?

```js
const container = this.shadowRoot.querySelector('.editor');
ace.edit(container, options);
```

so on initialisation here, we check if `getRootNode` exists (backwards compatibility) and if the result of it `!== document`. in which case, we (somehow) check if the styles have already been added to this root and add them if they haven't. but if it _is_ `document` or this browser doesn't support that method, we just append it to the `head` once.

if im missing something or thats too large of a change, though, your suggestion would be a good workaround. AFAIK you always do DOM selections and what not relative to a node so we should be safe there.

one thing we may encounter (which im also in the process of fixing in quill) is a problem with selection ranges, too. each root has its own selection from what i remember, but i would have to double check that.

**Comment by 43081j** [comment]
@nightwing  another thing is that the completion container will always be appended to the document body (for good reason). so the editor css must be in document scope **and** shadow scope anyway.

so your solution makes more sense in fact. because we want the current behaviour and the ability to add styles to a shadow root simultaneously. unless there's some non-css issues with being in a shadow tree, that should be enough.

**Comment by nightwing** [comment]
Luckily we do not use selection, so the attached pr should fix this issue

**Comment by rbirkgit** [comment]
This "fix" is causing our code to get duplicate ace <style> chunks and our editors use the duplicate css. Not sure if this is only happening on Angular apps or in other frameworks too. All our code that has projections or conditional statements (e.g. *ngIf) is causing local copies of the styles in "random" places in our code, in addition to styles being added to the document header. This because we have multiple ace editors in our code. None of our code use web components. Just plain Angular. I wish there was a way to force all styles in document header so we don't end up with all these duplicates.
