### ISSUE TITLE
Completions within brackets

### ISSUE THREAD

**Issue by tinderfields** [ajaxorg/ace#3786]
I've noticed that in general the completions in ace only work if the right bracket is not present.

For instance in the kitchen sink demo with "live autocompletions" turned on in HTML mode you can see the behaviour in the screengrabs below

Is this intended behaviour, common in all IDEs or particular to ACE?

If anyone has any idea how to get autocomplete working within brackets I'd be very interested.

Without brackets:
![screen shot 2018-09-28 at 15 32 01](https://user-images.githubusercontent.com/305689/46214937-1aca9580-c334-11e8-941c-38a589d8006b.png)

With brackets:
![screen shot 2018-09-28 at 15 31 48](https://user-images.githubusercontent.com/305689/46214967-2ae27500-c334-11e8-96fd-da426a103404.png)

**Comment by nightwing** [comment]
seems like this happens because https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/css_completions.js#L163 gets the state at the end of the line instead of the state at the cursor.

**Comment by robs-scc** [comment]
I have this problem too.  I want to provide multiple state changes per line, but it messes up the completions when the completions depend on the current token's state.

Within brackets, the state should be 'clause'. Outside of the brackets, it should be 'start'. There can be multiple clauses per line and nested clauses, so in the highlight rules, I use:
    `push:'clause'` // go into nested clause state
and:
   `next:'pop'` // leave nested clause state

In the completions, I want to use the token and state to determine which suggestions to display. Unfortunately, because there is only one state per line, I cannot get this to work.

**Comment by robs-scc** [comment]
In the session object, there is a getState(row).  See edit_session.js and background_tokenizer.js .  The tokenizer only provides one state (last state) per row (not per token).
