### ISSUE TITLE
ACE Editor Autocomplete is under different DOM Node

### ISSUE THREAD

**Issue by ktalebian** [ajaxorg/ace#3801]
I have my HTML page as

    <body>
       <div id="content">
         
         
    
    </body>

When I enable autoComplete, the DOM is not under `#content` bother rather `<body>`

    <body>
        <div id="content">
             <ace-editor>
        <div class=" ace_editor ace_autocomplete ace-chrome">

This is causing a lot of issues for number of reasons (I can provide more detail if needed). But how do I make sure that the auto complete is under of the same dom-node? Ideally I want

    <div id="content">
       <ace-editor>
       <auto-complete>

Or even
    
    <div id="content">
        <ace-editor>
           <auto-complete>

**Comment by nightwing** [comment]
Currently there is no way to chose to which element autocomplete popup is added, what issues does it cause now?

**Comment by vinothwindows47** [comment]
@nightwing , Why did you use Autocomplete feature using AceEditor Render instead of using DOM element. Because we are facing horizontal scrollbar issue if the autocomplete content is too long.If it is DOM that we can easily give horizontal scrollbar. But now it is difficult to handle it because of ACE renderer using. Please provide horizontal scrollbar in ACE AutoComplete PopUp. Already we have raised this issue about 2 months ago. We had tried to change in "popup.js" code.But we have failed to achieve this. Please do it.

**Comment by nightwing** [comment]
@ktalebian if you are using native fullscreen with `webkitRequestFullscreen` , then you can move the popup into another element with
```js
parentElement.appendChild(editor.completer.popup.container)
```
otherwise adding higher z-index for `.ace_editor.ace_autocomplete` should work
 it is now set to 200000 which may be behind the content in fullscreen mode.

A better way to chose the parent of the completer and tooltip popups will be useful, but it is a bit tricky to add, because all editors on the page use the same, popup for autocompletion.

@vinothwindows47 ace renderer was used because it doesn't slow down when there are many completion items, the issue with horizontal scrollbar is a bit hard to solve, i'll try to find some workaround before the next release.
