### ISSUE TITLE
Question: Custom events

### ISSUE THREAD

**Issue by Firebrand** [ajaxorg/ace#3807]
Love Ace editor. I'm trying to attach a mouseover event handler to one of the spans (ace_storage), however, it doesn't fire. As a matter of fact, trying to attach any kind of event handler to anything inside of the editor div doesn't work. Thanks in advance for your help!

**Comment by nightwing** [comment]
How do you plan to use the event listener?

There is no way to add event listener to a span, because of the way text inside the editor is rendered.

The recommended way is to attach event listener  to the editor and check if the cursor is over the interesting node or not, similar to https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/token_tooltip.js#L61.

**Comment by Firebrand** [comment]
@nightwing   Awesome suggestion. I think that's going to work quite beautifully. Many thanks!
