### ISSUE TITLE
typing the backtick character in editor should enclose selected text

### ISSUE THREAD

**Issue by tessus** [ajaxorg/ace#3954]
I've been searching the wiki and documentation, but I couldn't find anything to make this work. Strangely it works, when the editor type is set to `javascript`. Yet, when using the type `markdown` it does not.

2 things are rather strange:

- Enclosing text in markdown with a backtick character is a very common task. So why is this not supported by default?
- How can I make this work for the type `markdown` as well?

This came up in a ticket that was opened in the project Joplin. I really would like to be able to fix this in Joplin, but I don't know how. Maybe someone could add a section like `how to extend the range of characters to enclose selected text` to the documentation or FAQ?

I'd really appreciate any help with this.

/ref https://github.com/laurent22/joplin/issues/1426

**Comment by nightwing** [comment]
Thanks for bringing attention to this missing feature.
The automatic pairing of quotes is handled by the [cstyle behavior](https://github.com/ajaxorg/ace/blob/17696a233ff786a7726cff317ad849071d9fdf62/lib/ace/mode/behaviour/cstyle.js#L255) . I've added backtick to the list of default quotes for markdown in https://github.com/ajaxorg/ace/pull/3959/commits/e2adfefdeea85ba3f38a5a74f18adf596d056ea5.

**Comment by tessus** [comment]
@nightwing awesome, thank you.

Is this something I can do in userland by using an option or do I have to wait for the next ace release?
I really would like to fix this asap in Joplin. If it is not possible, I obviously have to wait, but I assume there is a way to manipulate the default quotes. I just couldn't finf it in the docs.

**Comment by nightwing** [comment]
You can add the $quote property to the mode similar to the commit.

**Comment by tessus** [comment]
Thanks

**Comment by tessus** [comment]
@nightwing sorry, but this seems to have a strange side effect. When trying to type 3 backticks (for a code block), the editor now creates 4 backticks and you have to delete one manually. This should only work for selected text but not when typing a single backtick character. Is there a way to fix this?

**Comment by innocuo** [comment]
I was debugging this on a different version of Ace, but maybe this helps:
on javascript mode, typing 3 backticks works ok.
on markdown mode, typing 3 backticks creates 4 (because it keeps pairing them).

in [csstyle behavior](https://github.com/ajaxorg/ace/blob/17696a233ff786a7726cff317ad849071d9fdf62/lib/ace/mode/behaviour/cstyle.js#L271), it gets the token. When it's javascript, the tick is of type "string.quasi.start", but on markdown it is of type "text.xml". CsStyle only prevents pairing if the string is of type "string" or "escape"

Adding something like this:

```
{
token : "text.language.escape",
regex : "`"
}
```
to the markdown highlight rules seems to fix it.

**Comment by nightwing** [comment]
@innocuo thanks for finding the source of the issue. I've tried to fix this without changing https://github.com/ajaxorg/ace/pull/3972 the highlight rules since sometimes triple quotes are used in js comments too and tokenizer doesn't help there.

Please test if this is fixed on https://raw.githack.com/ajaxorg/ace/misc/kitchen-sink.html?doc=Markdown

**Comment by tessus** [comment]
@nightwing yes, it seems that this fixes this. once again, any chance to fix this in userland? we use react-ace, which uses brace, which uses ace, so it will take a long time until all upstream packages are updated. We want to fix this right away, thus doing so in userland is the only way...

**Comment by nightwing** [comment]
@tessus you can call `editor.session.$mode.$behaviour.remove("string_dquotes")` `editor.session.$mode.$behaviour.add` with the modified function. And I'll try to help react-ace to use a newer version of ace.

**Comment by tessus** [comment]
@nightwing thanks again... it took a bit more than just re-adding the modified function. (I had to re-add both functions `insertion` and `deletion`, because the remove function deleted both. I also had to add vars and functions like `getWrapped` and `initContext`. I got it working though. If you are interested, this is what I did - https://github.com/laurent22/joplin/pull/1599/files
