### ISSUE TITLE
Characters stop showing up after the 10000th charater in a line

### ISSUE THREAD

**Issue by umbynos** [ajaxorg/ace#3983]
Tested this on the demo on Ace's website as well as on our software that uses Ace. 
If you paste a line longer than 10000 characters, all characters from the 10001st onwards are invisible. 
I confirmed they are indeed just not shown, and not actually spaces.

**Comment by Chocobo1** [comment]
Seems "the feature" is introduced in this commit: ace041c732def3c135ca03a93a4d1317f8b5901a
I wonder if there is a way to overwrite it?

**Comment by nightwing** [comment]
"The feature" was introduced because long lines are not rendered in chrome at all. 
Unfortunately there was a regression introduced later because of which the button is not visible. This regression should be fixed with https://github.com/ajaxorg/ace/pull/3989.
It is possible to restore the old behavior by using `editor.renderer.$textLayer.MAX_LINE_LENGTH=Infinity` but this is not very useful since browsers won't render the text anyway.

For the next release i'll try to add virtual viewport for horizontal scrolling too
