### ISSUE TITLE
Behavior of ctrl-p on Mac contradicts keyboard shortcut documentation

### ISSUE THREAD

**Issue by garybernhardt** [ajaxorg/ace#4029]
This documentation page (https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts) says that the default action for Ctrl-P on Mac is "Go line up". That behavior makes sense to me as a long-time Mac user; it's what Ctrl-P does in every text box on a Mac.

However, what ACE actually does when you hit Ctrl-P is "Go to matching bracket".

You can reproduce this by loading the kitchen sink editor (https://ace.c9.io/build/kitchen-sink.html) on a Mac and hitting Ctrl-P.

**Comment by nightwing** [comment]
Is this issue about the documentation not being up to date, or about the standard behavior of Ctrl-P being overriden?

Unfortunately issues with keyboard shortcut conflicts are rather hard to resolve because some users dislike the result in both cases, i agree that the decision to override Ctrl-P was wrong but not sure how to proceed. 

Are you using ace in your project or encountered the bug on a site using ace? If it is the former then the following temporary workaround can be used:
```js
var jumpCommand = editor.commands.byName.jumptomatching
editor.commands.removeCommand(jumpCommand)
command.bindKey.mac = "---"// something else
editor.commands.addCommand(jumpCommand)
```

**Comment by garybernhardt** [comment]
We're evaluating ACE as a possible replacement for another editor, so we could work around this with code like you showed. But I'm not very familiar with how the ACE project is run, so this issue is also an opportunity to learn about ACE's relationship to host platforms' UI norms.

My interpretation is that the docs are correct and this is a bug in ACE itself. As far as I can remember, I've never seen Ctrl-P fail to work in 15 years of use, even in web apps, even though I use it exclusively in place of the up arrow in text boxes. For someone who uses Ctrl-N/Ctrl-P as a complete replacement for up/down arrow, this mapping issue is equivalent to mapping the up arrow key to some other function. I'm confident that the ACE team would view a remap that breaks the up arrow as a bug. So my view is that ACE should be changed to match the Ctrl-P keyboard shortcut behavior that's ubiquitous on the Mac platform, as well as being specified in ACE's own docs.

(I didn't state a strong position like that in the initial issue because I didn't want to seem like I'm telling you how to run your project. If ACE's position is "host platform UI conventions are nice, but we won't break backwards compatibility to support them", then it probably just means that ACE has significantly different goals from ours and we should keep looking for a new text editor component.)

**Comment by nightwing** [comment]
The decision to change the default behavior of Ctrl-P have been made because multiple users have requested to enable jumptomatching command similar to windows version, and because the Ctrl-N shortcut have been overridden in cloud9 ide for several years prior to that, and no user have complained about it. And In 4 years since the Ctrl-P change you are the first to report this issue.

However i agree  that independently from the number of people using Ctrl-N/Ctrl-P for navigation, remapping one of main keys is a much more serious disruption, than remapping jumpToMatching, so i have opened a pull request that changes jumpToMatching keys to  cmd-\ and  cmd-shift-\, which also have the advantage of matching with the key used in vscode.

**Comment by garybernhardt** [comment]
That sounds like a very reasonable change history, and lining up with vscode definitely seems nice when possible.

Just to confirm, I double-checked and the other most common Emacs-style navigation keystrokes (Ctrl-N, Ctrl-F, Ctrl-B, Ctrl-A, Ctrl-E) all seem to work as normal in the editor on the site, so Ctrl-P seems to have been the only one that was remapped.

Thanks for making that PR!
