### ISSUE TITLE
"(Un)Fold all" shortcut for mac uses windows keymapping

### ISSUE THREAD

**Issue by jooleeanh** [ajaxorg/ace#4239]
OS version: MacOS Catalina 10.15.3

I'm using Postman Version 7.21.1 (7.21.1) which uses Ace text editor for its API response.
The Fold All shortcut, which for mac is cmd-alt-0 used to work (about 6 months ago), and now doesn't work anymore. After a bit of testing I realized that the shortcut alt-0 is working, which is the shortcut for Windows/Linux. Did the shortcut get mixed around, is the doc outdated, or is my computer working weirdly ?
I tried on the following keyboard languages: US, US International - PC, French - Numerical, Canadian French - CSA. For these 4 languages, the alt-0 works, and cmd-alt-0 doesn't.

**Comment by nightwing** [comment]
I've tried to download postman but the main link on postman.com leads to the version 7.20.1, so not sure what have happened exactly. But the keybinding in ace had [not been changed ](https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js#L137), maybe postman developers decided to switch to a simpler shortcut. (In very old versions we used Alt-0 too, but had to change it because of conflict with text input on some keyboards).
