### ISSUE TITLE
The cursor doesn't move by swipe on Android

### ISSUE THREAD

**Issue by usernein** [ajaxorg/ace#4327]
Some android keyboards have a feature "swipe space bar to move cursor". It was working fine on Ace Editor with the app [SimpleKeyboard](https://github.com/rkkr/simple-keyboard) (version [3.19](https://github.com/rkkr/simple-keyboard/releases/tag/69)) but since the version [3.20](https://github.com/rkkr/simple-keyboard/releases/tag/70) Ace Editor is not moving the cursor
First i thought it was some issue of SimpleKeyboard, but i tried with GBoard and it also doesn't work, so i think it may be some incompatibility with the way that GBoard (and now SimpleKeyboard) does

**Comment by nightwing** [comment]
The change in behavior is caused by this commit https://github.com/rkkr/simple-keyboard/commit/5c1e49598965ccaccaeb1ecd9b4a4ee6222d5eff#diff-6064a774fc85066280117b1f7041a0adR756. Before that the keyboard was sending arrow key events, which were handled by ace, now it directly modifies the position of the cursor in text area, and browsers do not send any event to allow web-apps to detect that change.
