### ISSUE TITLE
Async editor

### ISSUE THREAD

**Issue by ErrorGamer2000** [ajaxorg/ace#4505]
I would like to be able to set the entire script as `async` so I can use `await` outside of an async function. How would I do this?

**Comment by andrewnester** [comment]
Could you elaborate and provide some code example of what are you trying to achieve?

**Comment by ErrorGamer2000** [comment]
@andrewnester Sorry for the bad question. I was a total noob when I asked this. What I was trying to ask was can somebody add sorry for top-level use of the `await` keyword on the editor. It (at least at the time of writing the question) shows a syntax error.

**Comment by marcolubian** [comment]
Hi, I'm having the same issue. Is there a way to setup the ace editor in order to consider its content in a top-level async context? My issue is that, if I write this inside the editor in `javascript` mode

```javascript
const p = async() => {
    await f();
};
```

I have no problem, but if I do any await inside the editor itself, it goes in error:

```javascript
const p = async() => {
    await f();
};
await p(); // this line will be highlighted in error
```

For what I've seen, the best would be to have an option that allows to consider the script as if it was written inside an async function. For example, changing the `this.onUpdate` method of javascript_worker.js with something like this:

```javascript
    ...
    this.onUpdate = function() {
        var value = this.doc.getValue();
        value = value.replace(/^#!.*\n/, "\n");
        if (!value)
            return this.sender.emit("annotate", []);

        var errors = [];

        // var start = new Date();
        valueTopLevelAsync = 'async function asyncFn() {\n' + value + '\n}';
        lint(valueTopLevelAsync, this.options, this.options.globals);
        //lint(value, this.options, this.options.globals);
        var results = lint.errors;
    ....
```
