### ISSUE TITLE
gqq is not supported in vim mode

### ISSUE THREAD

**Issue by jyn514** [ajaxorg/ace#4537]
Steps to replicate:
1. Go to https://play.rust-lang.org/?gist=655128806e9a0ac08f6ab55ab70a3a5e
2. Enable vim mode
3. Type `gqq`

Nothing happens. In vim, it wraps the line:
```
This is a very, very long line with lots of text and no word wrapping at all - it would be nice to
split it into multiple lines.
```
cc @shepmaster since this affects rust-playground.

**Comment by psvenk** [comment]
I think this was fixed in #4545; `gqq` seems to work fine at <https://raw.githack.com/ajaxorg/ace/master/kitchen-sink.html>. It seems that Rust Playground [uses](https://github.com/integer32llc/rust-playground/blob/51fbbbcaa8cb5327016ef381b4d17a9b45148448/ui/frontend/package.json) the [`ace-builds`](https://www.npmjs.com/package/ace-builds) package on NPM, so I suppose that this change will make it to Rust Playground (and Overleaf, if I understand correctly) if/when a new version of Ace is tagged.

**Comment by nightwing** [comment]
Version with support of gqq will indeed be released soon.

While i have your attention, do you know if there are  operators other than gU gu g~ gq that act linewise by repeating only the last character?

**Comment by jyn514** [comment]
Do you mean ones that have another modifier in front? Because there are many that act linewise: dd, cc come to mind but I'm sure there are others.

**Comment by nightwing** [comment]
Yes i mean the operators with more than one letter. With the same logic with which `cc` and `dd` work , `gq` should be `gqgq`, but there is a shortened version `gqq`. So i was wondering if my implementation is correct or there is a case when `<key1><key2>` is an operator but `<key1><key2><key2>` is not equivalent to `<key1><key2><key1><key2>`

**Comment by jyn514** [comment]
I don't know, sorry.

**Comment by nightwing** [comment]
That's still a quite useful reply, it means that even if i am wrong, the operator behaving differently is a rarely used feature,

**Comment by psvenk** [comment]
@nightwing Sorry to bother you, but do you have an idea of when the new version will be tagged? I just want to make sure that this feature eventually goes downstream, in case you have forgotten about it. Thank you for Ace and for this feature!

Also, in response to your question, I too do not know of any other Vim operators `<key1><key2>` for which `<key1><key2><key2>` is not equivalent to `<key1><key2><key1><key2>`.

If there were any, they would probably be the ones where `<key2>` is a movement command. For example, if `g$` were an operator, then `g$` could mean "perform `g$$` from the cursor position to the end of the line (`$`)" or "perform `g$` on the entire current line". It seems that the latter would be the preferred interpretation — that is, this would not create any exceptions to the general rule that you identified — because `gw` is an operator and `gww` means "format the current line", not "format until the end of the current word (`w`)". This leads me to believe that there are no exceptions and that your implementation is correct in all cases.

**Comment by andrewnester** [comment]
It's been already released in latest Ace release, closing the issue
