### ISSUE TITLE
I can't place the cursor at the end of this line. 

### ISSUE THREAD

**Issue by ducaoya** [ajaxorg/ace#4579]
This is my code.
```
<ACEditor
    value={this.store.state.newValue}
    onChange={(value) => { this.store.setNewValue(value) }}
    theme="xcode"
    name="senior_editor"
    fontSize={13} 
    style={{ width: '100%', maxHeight: 800 }}
    showPrintMargin={false}
    setOptions={{
        enableSnippets: true, 
        showLineNumbers: true,
        tabSize: 4,
        wrap: true,
    }}
></ACEditor>
```
![image](https://user-images.githubusercontent.com/63651694/142374927-5efac19d-8822-42ef-a776-5742fbb73a3a.png)

**Comment by andrewnester** [comment]
At the moment because the wrap is configured to true if you move the cursor to the next character, it gets set to the start of the next line instead end of previous line. This is a default behaviour for Ace. Potentially, we can add a `bias` option similar to CodeMirror to configure either set the cursor to the end on line or the start of next line

**Comment by andrewnester** [comment]
Related to this, so I close as duplicate https://github.com/ajaxorg/ace/issues/2858
