### ISSUE TITLE
Editor: Doesn't support ANSI

### ISSUE THREAD

**Issue by ananthi-tg** [ajaxorg/ace#4824]
### Describe the bug

ANSI color codes like \u001b[1m are rendered as it is in the Editor. Is there a way to color the text?

### Expected Behavior

The corresponding text should be colored using the mentioned ANSI color code

### Current Behavior

Text isn't colored, rather editor displays the code

### Reproduction Steps

Pass value to the Ace Editor containing ANSI color codes, it will render the codes in the Editor

### Ace Version

9.4.0

**Comment by nightwing** [comment]
This can't be the default behavior of the editor, since code editor is supposed to show all the code and color it based on syntax.

But this behavior can be useful for a log viewer. Could you describe your usecase in little more detail, is editor supposed to be readonly, or should it allow deleting and inserting ansi codes too?

**Comment by Passiday** [comment]
I can join in with our usecase: we are trying to use the Ace Editor for the following two contexts:
- as a read-only log viewer, where the log lines are added live (when there's some background process going on)
- as a terminal-emulation window where user can input non-formatted command at the bottom, the command is passed to http API, and the command response is added to the bottom of the body.

We are looking also into possibilities to implement clickable links in the outputted text, I'm adding this because that also is related to non-displayed characters as there's need to supply link action metadata.

**Comment by choweiyuan** [comment]
Would like to see support for this

**Comment by meowcat** [comment]
Also interested!

**Comment by MatejPucihar** [comment]
+1

**Comment by rmonat** [comment]
Here is a [jsFiddle](https://jsfiddle.net/pxksydjt/) doing some kind of rendering for some ANSI escape codes. One fundamental limitation of the approach is that the escape sequences are still within the text editor. They are not displayed but they mess up the cursor placement, edition or copy-pasting. I would be curious to know if there would be workarounds to avoid that?
