### ISSUE TITLE
Python: smartquotes with f-strings

### ISSUE THREAD

**Issue by jasonmotha** [ajaxorg/ace#5063]
### Describe the bug

When using python in an editor typing `print(f"{test}")` results in a smart quote being added on the second quote but not the first.

### Expected Behavior

I'd expect a smartquote to be added on the first quote.

### Current Behavior

A smartquote is added when you are closing the quote on the f-string.

### Reproduction Steps

typing `print(f"{test}")` 

Or any f-string with a variable.

### Possible Solution

Detecting parameters that create f-strings

### Additional Information/Context

This might also be a problem for raw strings in python.

### Ace Version / Browser / OS / Keyboard layout

I tested this on the live version too https://ace.c9.io/build/kitchen-sink.html -- browser is firefox, also reproduced in chrome.

**Comment by InspiredGuy** [comment]
Thanks for the the report! The issue seems to be that current behaviour, used for the `python` mode, prevents second quote to be added if there is a word before the first quote - https://github.com/ajaxorg/ace/blob/master/src/mode/behaviour/cstyle.js#L264. Creating a new behaviour for Python, which would add a check for that syntax-specific symbol present in front of the first quote to prevent returning `null` instantly, might fix this issue. The check in the new behaviour could be something like `if ((isWordBefore && wordBefore !== 'f') || isWordAfter)`.

**Comment by alnmrata** [comment]
Uploading 529896da-673d-d2ce-12fc-82916146c2d1-main.mp4 …

**Comment by alnmrata** [comment]
[@alnmrata

**Comment by alnmrata** [comment]
> Uploading 529896da-673d-d2ce-12fc-82916146c2d1-main.mp4 …
> 
>

**Comment by andrewnester** [comment]
Released in 1.16.0
