### ISSUE TITLE
Tooltips are missing Ace themes

### ISSUE THREAD

**Issue by oykuyilmaz** [ajaxorg/ace#5100]
### Describe the bug

Tooltips don't get styled according to the theme, please see the screenshot below. 

### Expected Behavior

Tooltips have styles according to the theme set.

### Reproduction Steps

1. https://ace.c9.io/build/kitchen-sink.html
2. Change theme (e.g. Dark Monokai)
3. Enable live autocompletion
4. Hover on an autocomplete item with tooltip 

![Screenshot 2023-03-22 at 09 25 39](https://user-images.githubusercontent.com/12100596/226844100-6146c21e-0bf3-4c04-92a1-e8026baa6179.png)

**Comment by InspiredGuy** [comment]
Tooltips may have text content and html content, and for html content I think it's not feasible to style it since what may appear there is user-provided content. Maybe adding a class on the tooltip itself, which corresponds to the active theme, would help styling the content there. We do something similar for the editor itself.  Curious about your opinion @nightwing, would this lead to significant changes to prevent theme styles messing up with user html?

**Comment by nightwing** [comment]
In cloud9 we already do this by adding ace_dark class to the tooltip when the theme has `isDark` flag. It doesn't interfere with html, because html only provides basic markdown stuff, things like bold and links, colors are determined by the themes, I think this should be easy to fix, i'll take a look.
