### ISSUE TITLE
support SAS language

### ISSUE THREAD

**Issue by Mr-ZBin** [ajaxorg/ace#5399]
### Describe the feature

Hi,
Could anyone provides SAS language highlight?

### Use Case

SAS is a widely used statistical language.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

any version

**Comment by InspiredGuy** [comment]
Hi @Mr-ZBin, thank you for your request. Are there any formal syntax rules defined for SAS language which could be used to make a set of syntax highlighting rules? A PR to implement those would be welcome, see an example https://github.com/ajaxorg/ace/pull/5356

**Comment by Mr-ZBin** [comment]
Hi @InspiredGuy, I'm not good at this project, but I'll try it. And there are some contents for your reference to this request.
[SAS-Syntax in Visual Studio Code](https://github.com/77QingLiu/SAS-Syntax-and-Theme/blob/master/syntax/SAS%20Basic.sublime-syntax)
[SAS in pygments](https://github.com/pygments/pygments/blob/master/pygments/lexers/sas.py)

Thanks for your help.

**Comment by InspiredGuy** [comment]
Thank you @Mr-ZBin, a PR with your changes would be appreciated. You can follow the example in this PR https://github.com/ajaxorg/ace/pull/5356 to see where you need to put the new mode files, and which files you need to modify in order to make your mode available on the demo page and in TypeScript. Tests for the highlight rules are welcome as well.
