### ISSUE TITLE
This area(Code Number Column) is too wide and not very attractive. Can we make it narrower

### ISSUE THREAD

**Issue by swanfly** [ajaxorg/ace#5476]
### Describe the feature

This area(Code Number Column) is too wide and not very attractive. Can we make it narrower
![WX20240127-181825@2x](https://github.com/ajaxorg/ace/assets/5317370/dbde906a-e73b-4caa-ba57-47e3fa592e7a)

### Use Case

This area(Code Number Column) is too wide and not very attractive. Can we make it narrower
![WX20240127-181825@2x](https://github.com/ajaxorg/ace/assets/5317370/88568227-13db-442e-92a6-03d41293a920)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

v1.32.3

**Comment by swanfly** [comment]
<img width="424" alt="image" src="https://github.com/ajaxorg/ace/assets/5317370/1a614a5c-c7a9-4f75-bbc5-8711533de19a">

**Comment by nightwing** [comment]
The left padding is large by default to be able to display linter icons and breakpoints. It can be configured with css.

`editor.setOption("fixedWidthGutter", false)` to use width of largest visible line number instead of  largest number in the document.

`.ace_gutter-cell {padding-left: 0!important;}` use css to completely remove left padding 

`editor.renderer.$gutterLayer.$computePadding()` call this if you change the css after initializing the editor
