### ISSUE TITLE
Format selection (Beautify)

### ISSUE THREAD

**Issue by msaimraz** [ajaxorg/ace#5534]
### Describe the bug

Chrome's Ctrl-Shift-B shortcut for showing and hiding bookmark bars clashes with code formatting commands, making formatting difficult.

### Expected Behavior

format code

### Current Behavior

unable to format code in Chrome as the shortcut to format is Ctrl-Shift-B and it's also an Chrome shortcut to show and hide bookmark bars a

### Reproduction Steps

Ctrl-Shift-B

### Ace Version / Browser / OS / Keyboard layout

Google Chrome

**Comment by marinsokol5** [comment]
Hey, 
thanks for letting us know! 

I can't replicate on Mac, because Chrome has different shortcuts there and formatting works as expected. 

But I can indeed confirm based on https://support.google.com/chrome/answer/157179 -> Windows & Linux -> Google Chrome feature shortcuts -> Show or hide the Bookmarks bar, that it does indeed conflict. 

Source code is at https://github.com/ajaxorg/ace/blob/7869158657b5ea7b6e1b227b6a68979bca574263/src/ext/beautify.js#L407

To be honest, I am not entirely sure what would be a better keyboard shortcut, there's not a lot of them left after OS and browser take up their share. 
We can think a bit about it, but for now, I would recommend using the command palette through pressing F1 and then searching for format inside of it.

As a consumer, you can also change that particular keybinding, through either `editor.commands.bindKey` or by changing the `bindKey` property of the object passed when getting `require("src/ext/beautify").commands[0]`.

**Comment by msaimraz** [comment]
Switching to Shift+Alt+F could be a better option as it's compatible with VS Code.
