### ISSUE TITLE
Console output warning

### ISSUE THREAD

**Issue by Elssia** [ajaxorg/ace#5655]
### Describe the bug

As long as you hold down the ctrl key on your keyboard, the console will output an error warning. I'm not sure if this is normal behavior or if the printing errors can be turned off with some configuration option。 I have used this plug-in in the official instance editor and aws console policy editor and the behavior can be completely reproduced. See screenshot below

### Expected Behavior

no error output

### Current Behavior

![image](https://github.com/user-attachments/assets/226b5cb3-cc44-4e22-999b-cf10fb1dff91)
![image](https://github.com/user-attachments/assets/84e59f97-f664-4a88-9523-88c11eef1836)

### Reproduction Steps

Hold down the ctrl key on your keyboard

### Ace Version / Browser / OS / Keyboard layout

latest version /chrome 129 /win10 / key 108

**Comment by nightwing** [comment]
This error is not generated by ace, most likely it is caused by one of extensions installed in your browser, since this is exactly the message generated by chrome.runtime.sendMessage api https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon

**Comment by Elssia** [comment]
> 此错误不是由 ace 生成的，很可能是由浏览器中安装的某个扩展程序引起的，因为这正是 chrome.runtime.sendMessage api 生成的消息https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon

OK, thank you for your hard work. I will close this issue
